#!/usr/bin/env bash

# link dotfiles from dotfiles dir to HOME
# (as seen at remy's github)

# Everything from etc/ links straight to ~
for arg in $( ls ~/dotfiles/etc/ ); do
  ln -sfn ~/dotfiles/etc/$arg ~/.$arg
done

echo
echo   Initializing Git submodules, this may take a while...
echo 
git submodule init
git submodule update
